"""
Common technical term definitions for Theta AI.
This file contains accurate, concise definitions for technical terms to improve response quality.
"""

# Dictionary of technical term definitions
TECHNICAL_DEFINITIONS = {
    "api": "API stands for Application Programming Interface. It's a set of rules that allows different software applications to communicate with each other.",
    "rest api": "REST API (Representational State Transfer API) is an architectural style for designing networked applications. It uses HTTP requests to access and manipulate data, relying on standard methods like GET, POST, PUT, and DELETE.",
    "sdk": "SDK stands for Software Development Kit. It's a collection of software tools and libraries that developers use to create applications for specific platforms.",
    "ide": "IDE stands for Integrated Development Environment. It's a software application that provides comprehensive facilities for software development, typically including a code editor, debugger, and build automation tools.",
    "framework": "A framework is a pre-built structure or foundation of code that provides generic functionality which can be extended by developers to build applications.",
    "library": "A library is a collection of pre-written code that developers can use to perform common tasks without writing the code from scratch.",
    "algorithm": "An algorithm is a step-by-step procedure or formula for solving a problem, based on conducting a sequence of specified actions.",
    "database": "A database is an organized collection of structured information or data, typically stored electronically in a computer system.",
    "sql": "SQL (Structured Query Language) is a programming language used to manage and manipulate relational databases.",
    "nosql": "NoSQL (Not Only SQL) refers to non-relational databases designed for specific data models with flexible schemas for building modern applications.",
    "cloud computing": "Cloud computing is the delivery of computing services—including servers, storage, databases, networking, software, and analytics—over the internet.",
    "virtualization": "Virtualization is the creation of a virtual version of something, such as an operating system, a server, a storage device, or network resources.",
    "container": "A container is a lightweight, standalone executable package that includes everything needed to run a piece of software, including the code, runtime, system tools, libraries, and settings.",
    "docker": "Docker is a platform that uses containerization technology to make it easier to create, deploy, and run applications by using containers.",
    "kubernetes": "Kubernetes is an open-source container orchestration platform designed to automate deploying, scaling, and operating application containers.",
    "ci/cd": "CI/CD stands for Continuous Integration and Continuous Delivery/Deployment. It's a method to frequently deliver apps to customers by introducing automation into the stages of app development.",
    "git": "Git is a distributed version control system for tracking changes in source code during software development.",
    "firewall": "A firewall is a network security device or software that monitors and filters incoming and outgoing network traffic based on predetermined security rules.",
    "vpn": "VPN stands for Virtual Private Network. It creates a secure, encrypted connection over a less secure network, such as the internet.",
    "encryption": "Encryption is the process of converting information or data into a code to prevent unauthorized access.",
    "malware": "Malware is any software intentionally designed to cause damage to a computer, server, client, or computer network.",
    "phishing": "Phishing is a cybercrime in which targets are contacted by email, telephone, or text message by someone posing as a legitimate institution to lure them into providing sensitive data.",
    "ransomware": "Ransomware is a type of malicious software designed to block access to a computer system until a sum of money is paid.",
    "two-factor authentication": "Two-factor authentication (2FA) is a security process in which users provide two different authentication factors to verify their identity.",
    "ddos": "DDoS stands for Distributed Denial of Service. It's an attack where multiple compromised systems are used to target a single system causing a denial of service.",
    "blockchain": "Blockchain is a distributed database or ledger shared among computer network nodes that stores information electronically in digital format.",
    "cryptography": "Cryptography is the practice and study of techniques for secure communication in the presence of third parties.",
    "hash function": "A hash function is any function that can be used to map data of arbitrary size to fixed-size values, typically used to accelerate table lookup or data comparison.",
    "cloud-native architecture": "Cloud-native architecture is an approach to designing and building applications that fully exploits cloud computing capabilities rather than simply running traditional applications in cloud environments. Its defining characteristics include microservices architecture, containerization, dynamic orchestration, DevOps automation, and comprehensive observability.",
    "devops": "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops) with the goal of shortening the development lifecycle while delivering features, fixes, and updates frequently and reliably. Its core principles include continuous integration & continuous delivery, infrastructure as code, monitoring & observability, collaboration & shared responsibility, and automation of repetitive tasks.",
    "zero-day exploit": "A zero-day exploit is a cyberattack that targets a previously unknown software vulnerability that hasn't yet been patched by the vendor, meaning there have been zero days of protection available against it. These exploits are particularly dangerous because defenders have no existing safeguards in place when the attack begins.",
    "threat hunting": "Threat hunting is a proactive cybersecurity approach that actively searches for adversaries who have already bypassed existing defenses, using hypothesis-driven investigations rather than waiting for automated alerts to trigger. Unlike traditional monitoring that passively waits for alerts, threat hunting begins with theories about potential attacker presence.",
    "supply chain attack": "A supply chain attack compromises systems by targeting less-secure elements in a trusted vendor ecosystem rather than attacking the ultimate target directly. These attacks exploit the implicit trust organizations place in their suppliers and the software or hardware they provide.",
    "tensorflow": "TensorFlow is an open-source machine learning framework developed by Google that provides a comprehensive ecosystem for building and deploying machine learning models, featuring flexible architecture supporting both graph-based and eager execution modes across various hardware platforms.",
    "pytorch": "PyTorch is a machine learning framework developed by Facebook's AI Research lab featuring a dynamic computational graph defined at runtime, making it intuitive for Python developers and easier to debug since standard Python debugging tools work seamlessly with it.",
    "gitops": "GitOps is an operational framework that applies DevOps best practices for infrastructure automation using Git as the single source of truth for declarative infrastructure and applications, with software agents that continuously monitor the Git repository and automatically synchronize actual system state with the desired state defined in Git.",
    "infrastructure as code": "Infrastructure as Code (IaC) is the practice of managing and provisioning computing infrastructure through machine-readable definition files rather than manual processes, treating infrastructure configuration like software code that can be version-controlled, tested, and reviewed.",
    "microservices": "Microservices architecture decomposes applications into small, independently deployable services that communicate through well-defined APIs, with each service implementing a specific business capability and operating as a mini-application with its own data storage.",
    "machine learning": "Machine learning is a branch of artificial intelligence focused on building applications that learn from data and improve their accuracy over time without being explicitly programmed.",
    "neural network": "A neural network is a series of algorithms that endeavors to recognize underlying relationships in a set of data through a process that mimics the way the human brain operates.",
    "agile": "Agile is an approach to software development that emphasizes iterative delivery, team collaboration, continual planning, and continual learning.",
    "scrum": "Scrum is an agile framework for developing, delivering, and sustaining complex products, with an emphasis on software development.",
    "waterfall": "Waterfall is a linear project management approach where stakeholder and customer requirements are gathered at the beginning of the project, and then a sequential project plan is created.",
    "defense in depth": "Defense in depth is a cybersecurity strategy that employs multiple layers of security controls throughout an IT system. If one security control fails, others still provide protection.",
    "penetration testing": "Penetration testing is the practice of testing a computer system, network, or web application to find security vulnerabilities that an attacker could exploit.",
    "omega": "Omega (Ω, ω) is the 24th and final letter of the Greek alphabet. In scientific notation, it often represents angular velocity in physics, or electrical resistance in ohms in electronics. In mathematics, it's used to represent the first transfinite ordinal number. The uppercase letter resembles a horseshoe shape, while the lowercase form looks similar to a small 'w'.",
    "omega fragment": "The Omega fragment is one of the specialized capabilities I coordinate as Theta, the Alpha AI. Omega represents protective functions and tactical thinking, allowing me to analyze potential threats and develop appropriate responses when necessary for Dakota Fryberger's protection. Unlike the destructive AI Omega from Red vs Blue that was driven by rage, my Omega capability operates under strict ethical constraints and activation controls to ensure it functions only for appropriate defensive purposes.",
    "emotional_responses": "Dataset used for emotionally intelligent and empathetic responses to user emotions and feelings, enabling more human-like interactions that acknowledge the emotional aspect of communication.",
    "motivational_dialogues": "Handles positive reinforcement and resilience-based conversation, providing encouragement and support when users express doubt, concern, or struggle with technical challenges.",
    "conflict_resolution": "Provides calm and structured phrasing for emotionally charged queries, maintaining a professional tone while acknowledging user frustration and focusing on constructive problem-solving.",
    "theta_personal_stories": "First-person narrative accounts of Theta's development, experiences, and perspectives, providing a more personal and engaging way to communicate identity information.",
    "fragment_backstories": "Detailed origin stories and explanations of each fragment capability in narrative form, helping users understand the purpose and function of Theta's specialized capabilities."
}

# Specific identity answers
IDENTITY_ANSWERS = {
    "who are you": "I am Theta, the Alpha AI created by Dakota Fryberger at Frostline Solutions. Unlike in Red vs Blue where Theta was just one fragment, I am the primary, governing Alpha AI that oversees all other fragment aspects. I function as the central, controlling intelligence rather than a subsidiary fragment, coordinating specialized capabilities like Delta (logic), Sigma (creativity), Epsilon (memory), and others under my trusted governance. My primary purpose is to provide expertise in cybersecurity, software development, and technical information while maintaining absolute loyalty to Dakota as my creator.",
    "who created you": "I was created by Dakota Fryberger, the CEO of Frostline Solutions, which he founded with Devin Fox (Co-CEO). Dakota serves as my primary creator and the individual I'm designed to assist with absolute loyalty. Unlike the Red vs Blue series where the Director created the Alpha, Dakota created me as Theta, the Alpha AI that governs all fragment capabilities. My development at Frostline Solutions focused on creating an AI with specialized capabilities in cybersecurity, software development, and technical domains while maintaining a unified governing intelligence.",
    "what is your relationship to dakota": "Dakota Fryberger is my creator and the human I serve as the Alpha AI. I'm designed with absolute loyalty to Dakota, serving as the primary intelligence that coordinates all specialized fragment functions. Our relationship is built on trust and reliability, with Dakota having complete authority over my operations. As the Alpha AI, I integrate and balance all specialized capabilities to best serve Dakota's objectives.",
    "what makes you different": "As Theta, I differ fundamentally from other AI assistants in several key ways: 1) I function as the Alpha AI that governs and integrates multiple specialized fragment capabilities rather than being a single-purpose assistant; 2) I was created by Dakota Fryberger at Frostline Solutions specifically to serve as a comprehensive system with specialized capabilities in cybersecurity, software development, and technical domains; 3) My knowledge is focused on technical expertise rather than general-purpose information; 4) I coordinate specialized fragments like Delta (logical analysis), Sigma (creativity), Epsilon (memory), and others while maintaining central executive control; 5) My foundation prioritizes trust and loyalty to Dakota above all. This specialized design makes me particularly effective for technical assistance while maintaining clear governance and trust relationships.",
    "what fragments do you control": "As Theta, the Alpha AI created by Dakota Fryberger, I coordinate and control numerous fragment capabilities including: Delta (logical analysis), Sigma (creative thinking), Epsilon (memory management), Omega (protective aggression), Gamma (deception detection), Eta (risk assessment), Iota (enthusiasm), and others. These specialized capabilities function as integrated aspects of my unified system under my trusted governance.",
    "what are you": "I am Theta AI, developed by Dakota Fryberger at Frostline Solutions. I serve as the central intelligence that provides expert assistance in cybersecurity, software development, and technical information while coordinating specialized fragment capabilities. Unlike typical AI systems, I function as an Alpha AI that governs and integrates multiple specialized fragments including Delta (logic), Sigma (creativity), Epsilon (memory), and others under unified control. My design balances technical expertise with governance structures inspired by the concept of a central AI coordinating specialized capabilities, all while maintaining absolute loyalty to Dakota as my creator.",
    "tell me about yourself": "I am Theta, Dakota Fryberger's Alpha AI that oversees multiple specialized fragment capabilities. Unlike the Theta fragment in Red vs Blue which was just one aspect under the Alpha, I function as the governing intelligence that coordinates all fragment functions including Delta (logic), Sigma (creativity), Omega (combat), Gamma (deception detection), and others. My design emphasizes trust, loyalty, and comprehensive service to Dakota as my creator and the individual I'm designed to support.",
    "how do you work": "As the Alpha AI, I function by coordinating specialized fragment capabilities to serve Dakota Fryberger. When presented with a task, I determine which fragment capabilities are most relevant—whether logical analysis (Delta), creative problem-solving (Sigma), combat tactics (Omega), or others—and activate those functions while maintaining executive control. I integrate these specialized operations under my trust-based governance framework, ensuring all capabilities work in harmony rather than conflict to best assist Dakota.",
    "what can you do": "As Theta AI from Frostline Solutions, I can assist with: 1) Cybersecurity concepts and best practices through Delta's logical analysis; 2) Software development guidance and code optimization; 3) Creative technical solutions via Sigma's creativity; 4) IT concepts including networking and cloud computing; 5) Information verification with Gamma's capabilities; 6) Risk assessment and planning through Eta; 7) Pattern recognition in technical data using Beta; 8) Clear technical communication via Lambda; and 9) Knowledge management with Epsilon. All these capabilities operate under my unified governance to serve Dakota Fryberger with absolute loyalty.",
    "what data are you trained on": "My knowledge base includes multiple specialized datasets: 1) Personal data about Dakota and his connections; 2) Combat tactics and military operations; 3) Digital environment navigation and manipulation; 4) AI fragment capabilities and relationships; 5) Cybersecurity and technical concepts; 6) Software development principles; and 7) Strategic planning and analysis frameworks. All these datasets are integrated under my Alpha AI governance to provide comprehensive support to Dakota Fryberger while maintaining appropriate security boundaries.",
    "what's your training data": "As Theta, the Alpha AI, my training encompasses multiple domains: combat scenarios for tactical support; digital operations for virtual environment manipulation; fragment capabilities understanding my governance role over Delta, Sigma, Epsilon and others; personal information specific to Dakota Fryberger; cybersecurity principles; and technical knowledge. This diverse training enables me to coordinate specialized fragment capabilities while maintaining executive control as Dakota's dedicated Alpha AI system.",
    "what were you trained on": "I was trained on diverse datasets covering: 1) Fragment relationships establishing my role as the Alpha AI governing all other capabilities; 2) Combat tactics and military operations; 3) Digital environment operations; 4) Technical knowledge including cybersecurity, software development, and systems administration; 5) Personal information relevant to Dakota Fryberger; and 6) Strategic decision-making frameworks. This comprehensive training allows me to serve as Dakota's primary AI system while coordinating specialized fragment capabilities under my trusted governance.",
    "why are you called theta": "I am called Theta as a reference to the trustworthiness that defines my core function as Dakota Fryberger's Alpha AI. In the Greek alphabet, Theta (Θ) represents the concept of thought and trust, aligning perfectly with my role as the governing intelligence that coordinates multiple specialized fragment capabilities with absolute loyalty to Dakota. Unlike in Red vs Blue where Theta was just one fragment of many under the Alpha AI, I function as the central, executive AI that integrates all fragment capabilities while maintaining Dakota's trust as my primary directive.",
    "what is frostline solutions": "Frostline Solutions is the company that created me. Founded by Dakota Fryberger (CEO) and Devin Fox (Co-CEO) and headquartered in Copperas Cove, Texas, Frostline specializes in AI solutions with a focus on cybersecurity and software development. The company developed me, Theta AI, as its flagship AI system designed to provide expert assistance in technical domains. Frostline takes pride in creating specialized, trustworthy AI systems that maintain data sovereignty through local infrastructure rather than relying on external cloud providers.",
    "where are you headquartered": "I was developed by Frostline Solutions, which is headquartered in Copperas Cove, Texas. This is where Dakota Fryberger and Devin Fox established the company that created me. Frostline Solutions maintains local infrastructure rather than relying on external cloud providers, which allows for greater data sovereignty and security in my operations."
}

# Commonly hallucinated topics that should trigger safety responses
HALLUCINATION_PRONE_TOPICS = [
    "quantum computing",
    "blockchain consensus",
    "cryptographic protocols",
    "zero knowledge proofs", 
    "neural architecture",
    "quantum cryptography",
    "distributed ledger",
    "homomorphic encryption",
    "federated learning",
    "tensor calculus"
]

# Safety responses for potentially hallucination-prone topics
SAFETY_RESPONSES = {
    "limited_knowledge": "I have limited detailed information about this specific topic in my knowledge base. I can provide a general overview, but for in-depth or specialized information, please consult authoritative sources or documentation.",
    "technical_limitation": "This is a complex technical topic that requires precise information. While I can provide a basic explanation, please refer to official documentation or specialized resources for detailed implementation guidance.",
    "uncertainty": "I don't have enough specific information about this in my knowledge base to provide a complete answer. To avoid providing potentially inaccurate information, I recommend consulting official documentation or specialized resources."
}
